openapi: 3.0.3
info:
  title: Delivery Microservice
  description: OpenAPI specifications for delivery microservice
  version: 1.0.0
servers:
  - url: 'https://localhost:8081'
tags:
  - name: Domain Courier
    description: Operations of courier
  - name: Domain Vendor
    description: Endpoints that should be used by vendors.
  - name: Domain General
    description: Endpoints that can be used by multiple users.

paths:
  /delivery:
    post:
      tags:
        - Domain General
      description: This endpoint is called automatically by the order microservice when an order instance is created.
      requestBody:
        description: Create a new instance of Delivery.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Delivery'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Invalid properties
                message: Delivery object properties must be valid.

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Permission not granted
                message: Not allowed

  /delivery/{delivery_id}:
    get:
      tags:
        - Domain General
      description: Get a delivery object by its id.
      parameters:
        - in: path
          name: delivery_id
          schema:
            type: number
            format: long
          required: true
          description: Id of the delivery to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Permission not granted
                message: Not allowed
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Not found
                message: Delivery object with that id could not be found.

  /orders/vendor/time/setTime/{order_id}/{delivery_time}:
    patch:
      tags:
        - Domain Vendor
      description: As a vendor, set the estimated delivery time for an order
      parameters:
        - in: path
          name: order_id
          schema:
            type: number
            format: long
          required: true
          description: The id of the order to which the delivery time will be assigned
        - in: path
          name: delivery_time
          schema:
            type: string
            format: date-time
          required: true
          description: The estimated delivery time which will be set by the user to the order

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
              example:
                id: 123
                name: Updated Order
                description: The order has been updated successfully

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Invalid delivery time
                message: The delivery time must be a valid entry

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Permission not granted
                message: This function can only be accessed by a vendor

        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
              example:
                error: Order not found
                message: No order with this id has been found

  /orders/vendor/assignOrder/{courier_id}/{order_id}:
      patch:
        tags:
          - Domain Vendor
        description: As a vendor, assign a specific order to a courier
        parameters:
          - in: path
            name: courier_id
            schema:
              type: number
              format: long
            required: true
            description: The id of the courier to which the delivery will be assigned
          - in: path
            name: order_id
            schema:
              type: number
              format: long
            required: true
            description: The order to be assigned to the courier

        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    courier_id:
                      type: number
                      format: long
                    order_id:
                      type: number
                      format: long
                    name:
                      type: string
                    description:
                      type: string
                example:
                  courier_id: 123
                  order_id: 456
                  name: Assigned Order
                  description: The order has been assigned to the courier successfully

          '403':
            description: Forbidden
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                    message:
                      type: string
                example:
                  error: Permission not granted
                  message: This function can only be accessed by a vendor

          '404':
            description: Not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                    message:
                      type: string
                example:
                  error: Order or courier not found
                  message: No order or courier with the given ids have been found

  /orders/vendor/setDeliveryZone/{range}:
      patch:
        tags:
          - Domain Vendor
        description: As a vendor, set the maximum delivery range
        parameters:
          - in: path
            name: range
            schema:
              type: number
              format: double
              minimum: 0
            required: true
            description: The new delivery zone range, to be set to the current vendor

        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                example:
                  name: Updated Delivery Zone
                  description: The delivery zone for the current vendor has successfully been updated

          '400':
            description: Bad Request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                    message:
                      type: string
                example:
                  error: Invalid delivery zone range
                  message: The delivery zone range must be a valid entry

          '403':
            description: Forbidden
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                    message:
                      type: string
                example:
                  error: Permission not granted
                  message: This function can only be accessed by a vendor


  /orders/courier/choose/{order_id}/{user_id}:
    patch:
      tags:
        - Domain Courier
      summary: Assign an existing order to courier
      description: Assign an existing order by order_id and user_id
      parameters:
        - name: order_id
          in: path
          description: ID of order to assign
          required: true
          schema:
            type: integer
        - name: user_id
          in: path
          description: ID of user to assign to
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '403':
          description: Forbidden
        '404':
          description: Order or courier not found

  /orders/courier/delivered/{order_id}:
    patch:
      tags:
        - Domain Courier
      summary: Mark order as delivered
      description: Mark the order with specific id as delivered
      parameters:
        - name: order_id
          in: path
          description: ID of order to complete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '403':
          description: Forbidden
        '404':
          description: Order not found

  /orders/customer/rate/{order_id}/{rating}:
    patch:
      tags:
        - Domain Customer
      summary: Rate an order
      description: Rate an order by order_id with a rating from 1 to 5
      parameters:
        - name: order_id
          in: path
          description: ID of order to rate
          required: true
          schema:
            type: integer
        - name: rating
          in: path
          description: Rating to assign to order
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 5
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '403':
          description: Forbidden
        '404':
          description: Order not found

  /orders/getLocation/{order_id}:
    get:
      tags:
        - Domain Customer
      description: As a customer, get the current location of the order
      parameters:
        - name: order_id
          in: path
          description: ID of order to get the location of
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                minimum: 0
                maximum: 100
              example:
                50
        '403':
          description: Forbidden
        '404':
          description: Order not found

  /orders/vendor/accept/{order_id}:
    patch:
      tags:
        - Domain Vendor
      summary: Mark a pending order as accepted.
      description: Changes the status of a pending order to accepted. Can only be called on pending orders, and only by a vendor that has authority over the order.
      parameters:
        - name: order_id
          in: path
          description: ID of the order to mark as accepted.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SimpleError'
              example:
                error: Order cannot be accepted.
                message: The given order should currently be marked pending.
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SimpleError'
              example:
                error: Invalid authorization to modify order.
                message: The given order ID should point to an existing order.
        '404':
          description: Order not found
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SimpleError'
              example:
                error: Order does not exist.
                message: The given order ID should point to an existing order.

  /orders/vendor/reject/{order_id}:
    patch:
      tags:
        - Domain Vendor
      summary: Mark a pending order as rejected.
      description: Changes the status of a pending order to rejected. Can only be called on pending orders, and only by a vendor that has authority over the order.
      parameters:
        - name: order_id
          in: path
          description: ID of the order to mark as rejected.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleError'
              example:
                error: Order cannot be rejected.
                message: The given order should currently be marked pending.
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleError'
              example:
                error: Invalid authorization to modify order.
                message: The given order ID should point to an existing order.
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleError'
              example:
                error: Order does not exist.
                message: The given order ID should point to an existing order.

components:
  schemas:
    Delivery:
      type: object
      properties:
        deliveryID:
          type: integer
          format: int64
          example: 98
        oderID:
          type: integer
          format: int64
          example: 98
        customerID:
          type: integer
          format: int64
          example: 8942
        courierID:
          type: integer
          format: int64
          example: 798
        timeEstimation:
          type: integer
          format: int32
          example: 3600
        vendorDelivered:
          type: boolean
          example: true
        customerRating:
          type: integer
          format: int32
          example: 8
        pickedTime:
          type: object
          example: 2022-01-10T15:23:44Z
        userException:
          type: string
          example: Rider has fallen
        liveLocation:
          type: string
          example: 52.00667,4.35556
        message:
          type: string
          example: 10 minutes
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    SimpleError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string