image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      # Only cache the gradle directory, as we do not use a shared cache
      - .gradle/
    policy: pull

build-delivery-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle delivery-microservice:assemble delivery-microservice:testClasses

checkStyle-delivery-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle delivery-microservice:checkstyleMain delivery-microservice:checkStyleTest
  allow_failure: false


PMD-delivery-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle delivery-microservice:pmdMain
  allow_failure: true

test-delivery-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: test
  variables:
    GOOD_COVERAGE: 92 # Pass pipeline
    MINIMUM_COVERAGE: 90 # Pass with warning
  script:
    - gradle delivery-microservice:test delivery-microservice:jacocoTestReport
    - coverage=$(cat delivery-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"| sed -E "s/<.*>//" | sed -E "s/Total//")
    - coverage=${coverage::-1}
    - echo "TestCoverage:$coverage%"
    - if [ $coverage -ge $GOOD_COVERAGE ]; then exit 0; fi
    - if [ $coverage -ge $MINIMUM_COVERAGE ]; then exit 1; fi
    - exit 2
  artifacts:
    paths:
      - ./coverage
  allow_failure:
    # Pass with warning else fail
    exit_codes:
      - 1
  coverage: /TestCoverage:(\d+)%/

